apiVersion: v1
kind: Service
metadata:
  name: te-agent-boutique
  labels:
    app: te-agent-boutique
spec:
  ports:
  - port: 80
    name: web
  - port: 443
    name: https
  clusterIP: None
  selector:
    app: te-agent-boutique
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: te-disk
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: te-agent-boutique
spec:
  selector:
    matchLabels:
      app: te-agent-boutique
  replicas: 1
  serviceName: "te-agent-boutique"
  template:
    metadata:
      labels:
        app: te-agent-boutique
    spec:
      containers:
      - name: te-agent-boutique
        image: thousandeyes/enterprise-agent:latest
        command: ["/sbin/my_init"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        env:
          - name: TEAGENT_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: te-credentials
                key: TE_ACCOUNT_TOKEN
          - name: TEAGENT_INET
            value: "4"
          - name: KUBERNETES
            value: "true"
          - name: AGENT_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                # StatefulSet metadata.name will be te-agent-boutique-0
                fieldPath: metadata.name
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        tty: true
        # subPathExpr: $(AGENT_NAME)/ creates a separate folder
        # for each agent on persistant volume, ensuring there is 
        # no conflict if multiple agents deployed
        volumeMounts:
          - name: vol-te-agent
            mountPath: /var/lib/te-agent
            subPathExpr: $(AGENT_NAME)/te-agent
          - name: vol-te-agent
            mountPath: /var/lib/te-browserbot
            subPathExpr: $(AGENT_NAME)/te-browserbot
          - name: vol-te-agent
            mountPath: /var/log/agent
            subPathExpr: $(AGENT_NAME)/log
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: vol-te-agent
      annotations:
        storage-class: te-disk
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
