apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: te-agent-boutique
spec:
  selector:
    matchLabels:
      app: te-agent-boutique
  replicas: 1
  template:
    metadata:
      labels:
        app: te-agent-boutique
    spec:
      # Node label must be applied; ex:
      # kubectl label nodes gke-cluster-1-pool-1-405898a6-u6xp tehost=host2
      nodeSelector:
        tehost: host2
      containers:
      - name: te-agent-boutique
        image: thousandeyes/enterprise-agent:latest
        command: ["/sbin/my_init"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        env:
          - name: TEAGENT_ACCOUNT_TOKEN
            valueFrom:
              secretKeyRef:
                name: te-credentials
                key: TEAGENT_ACCOUNT_TOKEN
          - name: TEAGENT_INET
            value: "4"
          - name: KUBERNETES
            value: "true"
          - name: AGENT_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                # StatefulSet metadata.name will be te-agent-boutique-0
                fieldPath: metadata.name
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "200m"
        tty: true
        volumeMounts:
          - name: vol-agent
            mountPath: /var/lib/te-agent
            subPathExpr: $(AGENT_NAME)/te-agent
          - name: vol-agent
            mountPath: /var/lib/te-browserbot
            subPathExpr: $(AGENT_NAME)/te-browserbot
          - name: vol-agent
            mountPath: /var/log/agent
            subPathExpr: $(AGENT_NAME)/log
      volumes:
        - name: vol-agent
          persistentVolumeClaim:
            claimName: te-pvc-1
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: te-pv-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/te-pv-1/
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: te-pvc-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: te-pv-1