# Serverless API backend running on AWS

service: order-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

#  stage: dev
#  region: us-east-1

functions:
  payments:
    handler: handler.payments
    timeout: 10
    events:
      - http:
          path: payments/transact 
          method: any